// <auto-generated />
namespace Manuals.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BirthDatefromDateTimetoDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BirthDatefromDateTimetoDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201602071335576_BirthDate from DateTime to Date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
