// Generated by IcedCoffeeScript 108.0.9
(function() {
  $(function() {
    $('#NewTag').typeahead({
      name: 'Tags',
      source: function(query, process) {
        var tags;
        tags = [];
        return $.getJSON('/Home/AutoCompleteTag', {
          term: query
        }, function(data) {
          $.each(data, function(i, val) {
            tags.push(val);
          });
          return process(tags);
        });
      }
    });
  });

}).call(this);
