// Generated by IcedCoffeeScript 108.0.9
(function() {
  Application.controller('CommentController', [
    '$scope', '$http', function($scope, $http) {
      $scope.Comments = [];
      $scope.NewComment = {};
      $http({
        method: 'GET',
        url: '/Templates/GetComments'
      }).success(function(data) {
        $scope.Comments = data;
      });
      $scope.Create = function(comment) {
        $http({
          method: 'POST',
          url: '/Templates/CreateNewComment',
          data: {
            model: comment
          }
        }).success(function(data) {
          $scope.Comments.add(comment);
        });
      };
      $scope.ChangeRating = function(comment, liked) {
        $http({
          method: 'POST',
          url: '/Template/ChangeCommentRating',
          data: {
            comment: comment,
            liked: liked
          }
        }).success(function(data) {
          comment.Rating = data.newRating;
        });
      };
    }
  ]);

  return;

}).call(this);
