// Generated by IcedCoffeeScript 108.0.9
(function() {
  Application.controller('CommentController', [
    '$scope', '$http', function($scope, $http) {
      var timerLoad, timerUpdate;
      $scope.Comments = [];
      $scope.NewComment = {};
      $scope.Page = 0;
      $(window).scroll(function() {
        if ($(window).scrollTop() + $(window).height() > $(document).height() - 1) {
          $scope.Page = $scope.Page + 1;
          return $scope.GetComments();
        }
      });
      $scope.GetComments = function() {
        $http({
          method: 'POST',
          url: '/Templates/GetCommentbyPage',
          data: {
            manualId: $scope.NewComment.ManualId,
            page: $scope.Page
          }
        }).success(function(data) {
          $scope.Comments = data;
        });
      };
      $scope.Create = function(comment) {
        $http({
          method: 'POST',
          url: '/Templates/CreateNewComment',
          data: {
            model: comment
          }
        }).success(function(data) {
          $scope.GetComments();
        });
      };
      $scope.ChangeCommentRating = function(comment, liked) {
        $http({
          method: 'POST',
          url: '/Templates/ChangeCommentRating',
          data: {
            comment: comment,
            liked: liked
          }
        }).success(function(data) {
          comment.Rating = data.newRating;
        });
      };
      $scope.DeleteComment = function(comment) {
        return $http({
          method: 'POST',
          url: '/Templates/DeleteComment',
          data: {
            comment: comment
          }
        }).success(function(data) {
          $scope.Comments.splice($scope.Comments.indexOf(comment), 1);
          return;
        });
      };
      timerUpdate = setInterval((function() {
        $scope.GetComments();
      }), 50000);
      timerLoad = setTimeout((function() {
        $scope.GetComments();
      }), 100);
    }
  ]);

}).call(this);
