// Generated by IcedCoffeeScript 108.0.9
(function() {
  Application.controller('CommentController', [
    '$scope', '$http', function($scope, $http) {
      var timerLoad, timerUpdate;
      $scope.Comments = [];
      $scope.NewComment = {};
      $scope.GetComments = function() {
        $http({
          method: 'POST',
          url: '/Templates/GetComments',
          data: {
            manualId: $scope.NewComment.ManualId
          }
        }).success(function(data) {
          $scope.Comments = data;
        });
      };
      $scope.Create = function(comment) {
        $http({
          method: 'POST',
          url: '/Templates/CreateNewComment',
          data: {
            model: comment
          }
        }).success(function(data) {
          $scope.GetComments();
        });
      };
      $scope.ChangeCommentRating = function(comment, liked) {
        $http({
          method: 'POST',
          url: '/Templates/ChangeCommentRating',
          data: {
            comment: comment,
            liked: liked
          }
        }).success(function(data) {
          comment.Rating = data.newRating;
        });
      };
      timerUpdate = setInterval((function() {
        $scope.GetComments();
      }), 5000);
      timerLoad = setTimeout((function() {
        $scope.GetComments();
      }), 100);
    }
  ]);

}).call(this);
