// Generated by IcedCoffeeScript 108.0.9
(function() {
  Application.controller('HomeController', [
    '$scope', '$http', function($scope, $http) {
      $scope.Manuals = [];
      $http({
        method: 'GET',
        url: '/Home/GetManuals'
      }).success(function(data) {
        $scope.Manuals = data;
      });
    }
  ]);

}).call(this);
