# Generated by IcedCoffeeScript 108.0.9
(->
  Application.controller 'HomeController', [
    '$scope'
    '$http'
    ($scope, $http) ->
      $scope.Manuals = []
      $http(
        method: 'GET'
        url: '/Home/GetManuals').success (data) ->
        $scope.Manuals = data
        return
      $scope.Tags = []
      $http(
        method: 'GET'
        url: '/Home/GetTags').success (data) ->
        $scope.Tags = data
        return
      return
  ]
  return
).call this
