(->
  Application.controller 'HomeController', [
    '$scope'
    '$http'
    ($scope, $http) ->
      $scope.Manuals = []
      $http(
        method: 'GET'
        url: '/Home/GetManuals').success (data) ->
        $scope.Manuals = data
        return

      $scope.ChangeRating = (manual, liked) ->
        $http(
          method: 'POST'
          url: '/Home/ChangeRating'
          data:
            manual: manual
            liked: liked).success (data) ->
          manual.Rating = data.newRating
          return
        return

      $scope.Tags = []
      $http(
        method: 'GET'
        url: '/Home/GetTags').success (data) ->
        $scope.words = []
        angular.forEach data, (item) ->
          flag=true;
          angular.forEach $scope.words, (word) ->
            if word.text==item.Name 
                word.weight+=1
                flag = false;
          if flag
             $scope.words.push
               text: item.Name
               weight: 1
               link: 'http://google.com'
             return
        return
      $scope.colors = [
        '#800026'
        '#bd0026'
        '#e31a1c'
        '#fc4e2a'
        '#fd8d3c'
        '#feb24c'
        '#fed976'
      ]

      $scope.update = ->
        $scope.words.splice -5
        return

      return
  ]
  return
).call this

# ---
# generated by js2coffee 2.1.0