// Generated by IcedCoffeeScript 108.0.9
(function() {
  Application.controller('HomeController', [
    '$scope', '$http', function($scope, $http) {
      $scope.Manuals = [];
      $http({
        method: 'GET',
        url: '/Home/GetManuals'
      }).success(function(data) {
        $scope.Manuals = data;
      });
      $scope.ChangeRating = function(manual, liked) {
        $http({
          method: 'POST',
          url: '/Home/ChangeRating',
          data: {
            manual: manual,
            liked: liked
          }
        }).success(function(data) {
          manual.Rating = data.newRating;
        });
      };
      $scope.Tags = [];
      $http({
        method: 'GET',
        url: '/Home/GetTags'
      }).success(function(data) {
        $scope.Tags = data;
      });
    }
  ]);

}).call(this);
