// Generated by IcedCoffeeScript 108.0.9
(function() {
  Application.controller('HomeController', [
    '$scope', '$http', function($scope, $http) {
      $scope.Manuals = [];
      $http({
        method: 'GET',
        url: '/Home/GetManuals'
      }).success(function(data) {
        $scope.Manuals = data;
      });
      $scope.ChangeRating = function(manual, liked) {
        $http({
          method: 'POST',
          url: '/Home/ChangeRating',
          data: {
            manual: manual,
            liked: liked
          }
        }).success(function(data) {
          manual.Rating = data.newRating;
        });
      };
      $scope.Tags = [];
      $http({
        method: 'GET',
        url: '/Home/GetTags'
      }).success(function(data) {
        $scope.words = [];
        angular.forEach(data, function(item) {
          $scope.words.push({
            text: item.Name,
            weight: 1,
            link: 'http://google.com'
          });
        });
      });
      $scope.colors = ['#800026', '#bd0026', '#e31a1c', '#fc4e2a', '#fd8d3c', '#feb24c', '#fed976'];
      $scope.update = function() {
        $scope.words.splice(-5);
      };
    }
  ]);

}).call(this);
