// Generated by IcedCoffeeScript 108.0.9
(function() {
  Application.controller('ProfileController', [
    '$scope', '$http', function($scope, $http) {
      $scope.Manuals = [];
      $scope.User = {};
      $scope.GetManuals = function() {
        return $http({
          method: 'POST',
          url: '/User/GetManualsByUserId',
          data: {
            Id: $scope.Id
          }
        }).success(function(data) {
          $scope.Manuals = data;
        });
      };
    }
  ]);

}).call(this);
