// Generated by IcedCoffeeScript 108.0.9
(function() {
  (function() {
    Application.controller('ProfileController', [
      '$scope', '$http', function($scope, $http) {
        $scope.Manuals = [];
        $http({
          method: 'GET',
          url: '/User/GetManuals'
        }).success(function(data) {
          $scope.Manuals = data;
        });
      }
    ]);
  }).call(this);

}).call(this);
