// Generated by IcedCoffeeScript 108.0.9
(function() {
  Application.controller('TestController', [
    '$scope', '$http', function($scope, $http) {
      $scope.fn = function() {
        alert('test');
      };
    }
  ]);

}).call(this);
