// Generated by IcedCoffeeScript 108.0.9
(function() {
  Application.controller('ThemeController', [
    '$scope', '$http', function($scope, $http) {
      $http({
        method: 'GET',
        url: '/Language/GetTheme'
      }).success(function(data) {
        $scope.Theme = data.result;
      });
      $scope.SaveTheme = function(Theme) {
        return $http({
          method: 'POST',
          url: '/Language/SaveTheme',
          data: {
            theme: Theme
          }
        }).success(function(data) {});
      };
    }
  ]);

}).call(this);
