// Generated by IcedCoffeeScript 108.0.9
(function() {
  Application.controller('ThemeController', [
    '$scope', '$http', function($scope, $http) {
      $http({
        method: 'GET',
        url: '/Language/GetTheme'
      }).success(function(data) {
        $scope.Theme = data.result;
      });
    }
  ]);

}).call(this);
