Application.controller 'VideoController', ($scope) ->
  $scope.code = ''
  return
Application.directive 'myYoutube', ($sce) ->
  {
    restrict: 'EA'
    scope: code: '='
    replace: true
    template: '<div style="height:600px;"><iframe style="overflow:hidden;height:100%;width:100%" width="100%" height="100%" src="{{url}}" frameborder="0" allowfullscreen></iframe></div>'
    link: (scope) ->
      scope.$watch 'code', (newVal) ->
        if newVal
          scope.url = $sce.trustAsResourceUrl('http://www.youtube.com/embed/' + newVal)
        return
      return

  }

# ---
# generated by js2coffee 2.1.0