// Generated by IcedCoffeeScript 108.0.9
(function() {
  Application.controller('VideoController', function($scope) {
    $scope.code = '';
  });

  Application.directive('myYoutube', function($sce) {
    return {
      restrict: 'EA',
      scope: {
        code: '='
      },
      replace: true,
      template: '<div style="height:600px;"><iframe style="overflow:hidden;height:100%;width:100%" width="100%" height="100%" src="{{url}}" frameborder="0" allowfullscreen></iframe></div>',
      link: function(scope) {
        scope.$watch('code', function(newVal) {
          if (newVal) {
            scope.url = $sce.trustAsResourceUrl('http://www.youtube.com/embed/' + newVal);
          }
        });
      }
    };
  });

}).call(this);
